DD_CU:
  target: dev
  outputs:
    dev:
      type: sqlserver
      server: localhost
      user: SA
      password: MICROSOFTsucksH4RD
      port: 1433
      database: DD_CU
      schema: dbo
      threads: 4
      driver: 'ODBC Driver 17 for SQL Server'
      encrypt: true
      TrustServerCertificate: yes
