version: 2

models:
  - name: anal_finance__table3
    description: "Aggregates staff and staff families total amounts and unique patients from KCMH and non-KCMH data."
    columns:
      - name: year
        description: "The year of the data."
      - name: CLAIMLCTNAME
        description: "Name of the parent organization."
      - name: StaffTotalAmount
        description: "Total amount for staff."
      - name: StaffUniquePatients
        description: "Unique patients count for staff."
      - name: StaffFamTotalAmount
        description: "Total amount for staff families."
      - name: StaffFamUniquePatients
        description: "Unique patients count for staff families."