version: 2

models:
  - name: stg_dataset__ipd_diag_icd10
    description: "Diagnosis of IPD patients"
    columns:
      - name: AN
        description: "Admission number"
      - name: INDATE
        description: "Admission date from inpatient summary"
      - name: DCHDATE
        description: "Discharge date from inpatient summary"
      - name: DIAGTYPE
        description: "Diagnosis type code"
      - name: DIAGTYPE_NAME
        description: "Name or description of the diagnosis type"
      - name: ITEMNO
        description: "Diagnosis item number"
      - name: ICD10
        description: "ICD-10 diagnosis code"
      - name: ICD10WHO
        description: "ICD-10 WHO standardized code"
      - name: DISEASE_NAME
        description: "Disease name associated with ICD-10 code"
      - name: DIAGKEY
        description: "Unique key for the diagnosis entry"
      - name: FIRSTDATE
        description: "Date of the first occurrence of the diagnosis"
  - name: stg_dataset__opd_diag_icd10
    description: "Diagnosis of OPD patients"
    columns:
      - name: HN
        description: "Patient number"
      - name: VSTDATETIME
        description: "Visit datetime, calculated by combining INDATE and INTIME (HHMMSS format)"
      - name: CLINICLCT
        description: "Clinic location code"
      - name: ITEMNO
        description: "Diagnosis item number"
      - name: AN
        description: "Admission number"
      - name: VN
        description: "Visit number"
      - name: ICD10
        description: "ICD-10 diagnosis code"
      - name: ICD10WHO
        description: "ICD-10 WHO standardized code"
      - name: DISEASE_NAME
        description: "Disease name associated with ICD-10 code"
      - name: DIAGTYPE
        description: "Diagnosis type code"
      - name: DIAGTYPE_NAME
        description: "Name or description of the diagnosis type"
      - name: DIAGKEY
        description: "Unique key for the diagnosis entry"
      - name: FIRSTDATE
        description: "Date of the first occurrence of the diagnosis"
  - name: stg_dataset__opd_proc_icd9cm
    description: "Outpatient procedures (ICD-9-CM)"
    columns:
      - name: HN
        description: "Patient number"
      - name: VSTDATETIME
        description: "Visit datetime, calculated by combining INDATE and INTIME (HHMMSS format)"
      - name: CLINICLCT
        description: "Clinic location code"
      - name: DSPNAME
        description: "Display name of the clinic location"
      - name: HCODE
        description: "Local hospital code used for internal categorization of services or departments"
      - name: ITEMNO
        description: "Procedure item number"
      - name: AN
        description: "Admission number"
      - name: VN
        description: "Visit number"
      - name: ICD9CM
        description: "ICD-9-CM procedure code"
      - name: PROC_NAME
        description: "Name or description of the ICD-9-CM procedure"
      - name: FIRSTDATE
        description: "Date of the first occurrence of the procedure"
  - name: stg_dataset__ipd_proc_icd9cm
    description: "Inpatient procedures (ICD-9-CM) with operating room usage and full procedure datetimes"
    columns:
      - name: AN
        description: "Admission number"
      - name: ITEMNO
        description: "Procedure item number"
      - name: ICD9CM
        description: "ICD-9-CM procedure code"
      - name: PROC_NAME
        description: "Name or description of the ICD-9-CM procedure"
      - name: USE_OR
        description: "Indicator whether the procedure used an operating room ('Y' or 'N')"
      - name: INDATETIME
        description: "Start datetime of the procedure, calculated by combining INDATE and INTIME (HHMMSS format)"
      - name: OUTDATETIME
        description: "End datetime of the procedure, calculated by combining OUTDATE and OUTTIME (HHMMSS format)"
      - name: FIRSTDATE
        description: "Date of the first occurrence of the procedure"
  - name: stg_dataset__cost
    description: "Costing and charge capture data from INCPT joined with order and patient type reference tables"
    columns:
      - name: HN
        description: "Patient number"
      - name: INCDATETIME
        description: "Datetime of the charge, calculated from INCDATE and INCTIME (HHMMSS format)"
      - name: ORDERCODE
        description: "Order or procedure code"
      - name: INCOME
        description: "Income group code associated with the order"
      - name: NAME
        description: "Order or procedure name from MASTERORDER"
      - name: ITEMNO
        description: "Item number within a receipt, representing a specific line item in the financial transaction"
      - name: AN
        description: "Admission number"
      - name: VN
        description: "Visit number"
      - name: PTTYPE
        description: "Patient type code"
      - name: PTTYPE_NAME
        description: "Patient type name from reference table"
      - name: PTTYPEEXT
        description: "Extended patient type code"
      - name: PTTYPEEXT_NAME
        description: "Extended patient type name from reference table"
      - name: DCT
        description: "Doctor code responsible for the order"
      - name: OVERTIME
        description: "Flag indicating if the order was made during overtime hours"
      - name: RFRLCT
        description: "Referral location code"
      - name: INCAMT
        description: "Amount charged for the order"
      - name: FINREFNO
        description: "Reference number of the invoice (ใบแจ้งหนี้); used for financial tracking and billing"
      - name: QTY
        description: "Quantity of the item or service ordered"
      - name: CANCELDATE
        description: "Date the order was canceled, if applicable"
      - name: FIRSTDATE
        description: "Date the order was first recorded"
      - name: FINLCT
        description: "Location related to financial handling or billing"
      - name: INCGRP
        description: "Income group or category"
      - name: RFINREFNO
        description: "Reference number for treatment cancellation (ยกเลิกการรักษา); links to the original financial transaction"
      - name: RCPTLCT
        description: "Receipt location code"
      - name: CASHFREQNO
        description: "Cash frequency or batch number"
      - name: EXPDATETIME
        description: "Datetime representing the expiration of the order or service, calculated from EXPDATE and EXPTIME (HHMM[SS] format)"
      - name: FEXP_REF
        description: "Reference to future expected expenses or adjustments"
      - name: WARD
        description: "Ward code where the patient stayed"
      - name: DSPNAME
        description: "Display name of the ward location"
      - name: ROOMNO
        description: "Room number assigned to the patient"
      - name: BEDNO
        description: "Bed number assigned to the patient"
  - name: stg_dataset__opd_visit_timeline
    description: "Detailed outpatient visit timeline with clinic info, timestamps for key events, and visit metadata"
    columns:
      - name: HN
        description: "Patient number"
      - name: VSTDATETIME
        description: "Datetime of the visit, constructed from VSTDATE and VSTTIME (HHMMSS format)"
      - name: HCODE
        description: "Local hospital code identifying the clinic location"
      - name: CLINIC_NAME
        description: "Display name of the clinic location"
      - name: CLINICTYPE
        description: "Type or category of clinic"
      - name: AN
        description: "Admission number (if linked to inpatient record)"
      - name: VN
        description: "Visit number"
      - name: DCT
        description: "Doctor code assigned to the visit"
      - name: IN_STATUS_NAME
        description: "Name of in status (from OVSTIST)"
      - name: OUT_STATUS_NAME
        description: "Name of out status (from OVSTOST)"
      - name: WEIGHT
        description: "Patient weight at the time of visit (kg)"
      - name: HEIGHT
        description: "Patient height at the time of visit (cm)"
      - name: NEXTDATETIME
        description: "Datetime the current visit was originally scheduled for (appointment datetime from NEXTDATE and NEXTTIME)"
      - name: OAPPNO
        description: "Appointment number or outpatient appointment reference"
      - name: KIOSKDATE
        description: "Date of kiosk check-in, if applicable"
      - name: NURSE_CALL_DATETIME
        description: "Datetime when nurse called the patient"
      - name: REGDATETIME
        description: "Datetime of patient registration, from REGDATE and REGTIME"
      - name: HISTORY_TAKING_DATETIME
        description: "Datetime of patient interview or history taking (from ITVDATE and ITVTIME)"
      - name: SNDDCTDATETIME
        description: "Datetime patient was sent to see the doctor (from SNDDCTDATE and SNDDCTTIME)"
      - name: DOCTOR_CALL_DATETIME
        description: "Datetime doctor called the patient"
      - name: MEET_DCT_DATETIME
        description: "Datetime of doctor-patient meeting (from MTDCTDATE and MTDCTTIME)"
      - name: COMPLETE_DISCHARGE_DATETIME
        description: "Datetime of visit discharge (from CMPDCTDATE and CMPDCTTIME)"
      - name: AGE
        description: "Patient age at time of visit"
      - name: AGEFLAG
        description: "Flag or indicator for age calculation or special age-related handling"
      - name: FIRSTDATE
        description: "Date the visit was first recorded"
      - name: CANCELDATE
        description: "Date the visit was canceled, if applicable"
  - name: stg_finance__vital_signs
    description: "Outpatient vital signs and triage data collected during visit, including blood pressure, temperature, and GCS"
    columns:
      - name: HN
        description: "Patient number"
      - name: VSTDATE
        description: "Visit date"
      - name: VSTTIME
        description: "Visit time"
      - name: CLINICLCT
        description: "Clinic location code"
      - name: ITEM
        description: "Item or observation index within the visit"
      - name: VN
        description: "Visit number"
      - name: FN
        description: "Form number or internal reference number"
      - name: PRDATETIME
        description: "Datetime the vital signs were recorded, from PRDATE and PRTIME (HHMMSS format)"
      - name: AN
        description: "Admission number"
      - name: LBPN
        description: "Low (diastolic) blood pressure in mmHg"
      - name: HBPN
        description: "High (systolic) blood pressure in mmHg"
      - name: PR
        description: "Pulse rate (beats per minute)"
      - name: RR
        description: "Respiratory rate (breaths per minute)"
      - name: BT
        description: "Body temperature (°C)"
      - name: O2SAT
        description: "Oxygen saturation (%)"
      - name: E
        description: "Eye response score in Glasgow Coma Scale (GCS)"
      - name: V
        description: "Verbal response score in GCS"
      - name: M
        description: "Motor response score in GCS"
      - name: GCS
        description: "Total Glasgow Coma Scale score (E + V + M)"
      - name: HCT
        description: "Hematocrit value (%)"
      - name: DTX
        description: "Capillary blood glucose (mg/dL)"
      - name: PS
        description: "Pain score"
      - name: PS2
        description: "Second pain score or alternative pain scale"
      - name: NOTE
        description: "Additional notes or observations from the triage nurse"
      - name: WEIGHT
        description: "Patient weight (kg)"
      - name: HEIGHT
        description: "Patient height (cm)"
      - name: HEADLINE
        description: "Head circumference or measurement (cm)"
      - name: CHESTLINE
        description: "Chest circumference or measurement (cm)"
      - name: WAISTLINE
        description: "Waist circumference (cm)"
      - name: HIPLINE
        description: "Hip circumference (cm)"
      - name: EMRGNCY
        description: "Flag indicating emergency status of the visit"
      - name: ZONELCT
        description: "Zone location within the clinic or triage area"
      - name: ROOMNO
        description: "Room number where the vitals were recorded"